# Generated by Django 5.2.7 on 2025-10-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Блог-пост', 'verbose_name_plural': 'Блог-посты'},
        ),
    ]
