# Generated by Django 5.2.7 on 2025-10-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='views_count',
            new_name='views',
        ),
    ]
