# Generated by Django 5.2.7 on 2025-11-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Опубликован"),
                    ("unpublished", "Снято с публикации"),
                ],
                default="published",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
