# Generated by Django 5.2.7 on 2025-11-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_unpublish_product",
                        "Может снимать с публикации, удалять и редактировать продукт",
                    )
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
